dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libsfml-dev
      - g++-7

before_install:
  - mkdir cmake-dist
  - travis_retry wget -qO- https://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz | sudo tar --strip-components=1 -C cmake-dist -xz
  - export PATH=$PWD/cmake-dist/bin:$PATH;

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - cd /usr/local
  - sudo wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz
  - sudo tar -xzf SFML-2.4.2-linux-gcc-64-bit.tar.gz
  - sudo cp -r SFML-2.4.2/include .
  - sudo cp -r SFML-2.4.2/lib .
  - sudo cp -r SFML-2.4.2/share .
  - sudo rm -rf SFML-2.4.2
  - cd -

before_script:
  #  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  #  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..

script:
  - make
